"""Add deep_analysis_data column

Revision ID: d9cfa71f101e
Revises: bf725578039b
Create Date: 2025-11-19 14:03:00.499561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9cfa71f101e'
down_revision = 'bf725578039b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deep_analysis_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_column('deep_analysis_data')

    # ### end Alembic commands ###
